my_name = input ("Please enter your name: ")
my_age = input ("Thank you for entering your name. Please enter your age: ")
my_height = input ("Thank you for entering your age. Please enter your height in inches: ")
my_weight = input ("Thank you for entering your height. Please enter your weight in pounds: ")
my_eyes = input ("Thank you for entering your weight. Please enter your colour of your eyes: ")
my_hair = input ("Thank you for entering your eye colour. Please enter your hair colour: ")
print (f"That's all the infomation I need at the momemt {my_name}")
print ("So lets recap your infomation")
print (f"Your Name is: {my_name}")
print (f"Your Age is: {my_age}")
print (f"Your Height is {my_height}Inches")
print (f"Your Weight is {my_weight}Pounds")
print (f"Your Eye colour is {my_eyes}")
print (f"Your Hair colour is {my_hair}")
